Implemented authentication with authjs
designthriving/designthriving pull request #24
Opened 2023-02-22 22:19 UTC by samuelili

Implemented providers are Google and Discord, and some helper code has been implemented for making protecting routes simple.

2023-02-22 22:26 UTC, Kevin-D23 commented
Not too familiar with using Auth, but from what I can understand, looks good to me!

2023-02-22 23:39 UTC, tomli380576 requested changes
Looks good!

2023-02-22 23:39 UTC, tomli380576 commented on types/next-auth.d.ts
> +        user: GoogleProfile & User;
is `GoogleProfile` guaranteed to exist if the user uses discord to sign in?

2023-02-22 23:39 UTC, tomli380576 commented on src/datastore/UserCollection.ts
> +      message: email?.toString()
wait I just realized email is already a string, so you don't need to use either optional chaining or the `.toString()` method

2023-02-22 23:39 UTC, tomli380576 commented on src/datastore/UserCollection.ts
>        friends.push(await this.getUser(friend._id, {
use Promise.all instead of for-await

2023-02-22 23:39 UTC, tomli380576 commented on src/utils/protectRoute.ts
> +export default async function protectedGetServerSideProps(context: GetServerSidePropsContext): Promise<GetServerSidePropsResult<object>> {
I'm assuming this is just a test implementation so the return type is not specified. When we actually implement this route the inner type parameter should not be `object`

2023-02-22 23:54 UTC, tomli380576 commented on src/datastore/UserCollection.ts
>        friends.push(await this.getUser(friend._id, {
`Promise.allSettled` is also an option if you want the error objects

2023-02-23 01:26 UTC, samuelili commented on src/datastore/UserCollection.ts
> +    throw {
I recognize the Result<T, E> thing! That's like golang. I like it, I'll go ahead and implement it.

2023-02-23 01:33 UTC, tomli380576 commented on src/datastore/UserCollection.ts
> +    throw {
There's an existing library for all sorts of monads like `Result<T, E>` https://github.com/gvergnaud/ts-pattern but note that this only applies to our application. External api calls can still throw exceptions

2023-02-23 01:40 UTC, samuelili commented on src/utils/protectApiRoute.ts
> +    return session;
res.send is fine here.

Modified it so that it throws a `NotAuthenticatedError`

2023-02-23 01:44 UTC, samuelili commented on pages/api/auth/[...nextauth].ts
> +          user = await instance.users.getUserByEmail(session.user.email);
I think that defeats the purpose of async/await.
I also realized that as of right now we don't really need to keep the profile given to us by the providers, so I've changed it to just straight up replace session.user with a User object.

2023-02-23 01:44 UTC, samuelili commented on src/datastore/UserCollection.ts
> +      message: email?.toString()
Fixed thanks to a `UserNotFoundError`!

2023-02-23 01:47 UTC, samuelili commented on src/datastore/UserCollection.ts
>      for (const friend of user.friends || []) {
Done

2023-02-23 01:47 UTC, samuelili commented on types/next-auth.d.ts
> +        user: GoogleProfile & User;
No, I forgot to do fix this lmao

2023-02-23 01:50 UTC, samuelili commented on src/datastore/UserCollection.ts
>        friends.push(await this.getUser(friend._id, {
Addressed! Thanks, you helped me remember how to use Promise.all with async await

2023-02-23 01:50 UTC, samuelili commented on src/utils/protectRoute.ts
> +export default async function protectedGetServerSideProps(context: GetServerSidePropsContext): Promise<GetServerSidePropsResult<object>> {
Yeah. Ideally this would actually take in a function so we can still use getServerSideProps with the added route protection. For a later time!

2023-02-23 03:20 UTC, tomli380576 commented on src/Result.ts
> +    error: E | null
Wouldn't this require `value` to always exist? I think you are looking for this:
```ts
type Result<T, E extends Error = Error> =
    | { ok: true; value: T }
    | { ok: false; error: E };
```
with 2 helper functions:

```ts
const Ok = <T>(val: T): { ok: true; value: T } => ({ ok: true, value: val });
const Err = <E extends Error>(err: E): { ok: false; error: E } => ({
    ok: false,
    error: err
});
```

2023-02-23 03:24 UTC, tomli380576 commented on src/datastore/UserCollection.ts
> +      }) as Friend));
Did you mean to call the `Friend` constructor here?

2023-02-23 03:26 UTC, tomli380576 commented on types/next-auth.d.ts
> +        user: GoogleProfile | DiscordProfile | User;
Did you mean to use `(GoogleProfile | DiscordProfile) & User)`?

2023-02-23 03:27 UTC, tomli380576 commented on types/next-auth.d.ts
> +        user: GoogleProfile | DiscordProfile | User;
Or maybe we can drop the google profile and discord profile altogether and just have user instead. The user constructor could depend on `GoogleProfile` or `DiscordProfile` but I'm not sure

2023-02-23 03:36 UTC, tomli380576 reviewed
Ready to merge!

2023-02-23 03:36 UTC, tomli380576 approved these changes

2023-02-24 00:15 UTC, tomli380576 commented on src/Result.ts
> +    error: E | null
Example:
```ts
function oddNumberOnly(num: number): Result<number, Error> {
    if (num % 2 === 0) {
        return Err(new Error('this function only accepts odd numbers'));
    }
    return Ok(num);
}
```

2023-02-24 02:00 UTC, Kevin-D23 commented on pages/_app.tsx
> +import { getServerSession } from 'next-auth';
Might just be an issue on my end, but couldn't get it to run unless I changed it to `'next-auth/next'`.

2023-02-24 20:13 UTC, samuelili commented on pages/_app.tsx
> +import { getServerSession } from 'next-auth';
Good note, I'll change it to that just to make sure it'll run fine

2023-02-24 20:17 UTC, merged