UI: sidenav
designthriving/designthriving pull request #25
Opened 2023-02-26 10:48 UTC by jackie-ou

refactor: aligned css
feat: toggle selected tab
feat: online status toggler
todo: fetch mock data
todo: refactor CSS names to ditch BEM

2023-02-27 00:21 UTC, tomli380576 requested changes

2023-02-27 00:21 UTC, tomli380576 commented on components/SideNav.tsx
> +  const handleChange = (e: any) => {
The type for `e` is `React.ChangeEvent<HTMLSelectElement>`

2023-02-27 00:21 UTC, tomli380576 commented on components/SideNav.tsx
> +    if (onlineStatus == 1) {
Use `===` instead of `==`

2023-02-27 00:21 UTC, tomli380576 commented on components/SideNav.tsx
> +              onChange={(e) => handleChange(e)}
very minor thing but since the call signature of `handleChange` matches `onChange`,  you can directly write:
```ts
onChange={handleChange}
```

2023-02-27 00:21 UTC, tomli380576 commented on styles/Sidenav.module.css
> +  font-size: 16px;
relative units

2023-02-28 10:32 UTC, jackie-ou commented on components/SideNav.tsx
> +  const handleChange = (e: any) => {
Tried this code broke, not sure how to fix. Left untouched for now.

2023-02-28 10:33 UTC, jackie-ou commented on components/SideNav.tsx
> +    if (onlineStatus == 1) {
Done

2023-02-28 10:43 UTC, jackie-ou commented on components/SideNav.tsx
> +              onChange={(e) => handleChange(e)}
Tried this code broke, not sure how to fix. Left untouched for now.

2023-02-28 10:56 UTC, jackie-ou commented on styles/Sidenav.module.css
> +  font-size: 16px;
Done

2023-03-02 01:01 UTC, samuelili commented on components/SideNav.tsx
> +  const handleChange = (e: any) => {
Issue #26 created for implementing route for changing user's status

2023-03-02 01:04 UTC, samuelili commented
Looks great! The component definitely is getting really bloated, but that should be an easy fix :)

2023-03-02 01:04 UTC, samuelili approved these changes

2023-03-03 02:53 UTC, jackie-ou commented
- UI is finalized
- the component is bloated and could use some refactoring

2023-03-03 02:54 UTC, merged